### ISSUE TITLE
help running sugar-build with docker and docker-compose

### ISSUE THREAD

**Issue by nemesiscodex** [sugarlabs/sugar-build#46]
Hi guys, I'm trying to setup and run sugar-build in a docker container with no luck so far. I just wanted to standardize and package all sugar dependencies and be able to develop in any unix platform without having to use fedora.

The idea is to run sugar-build like this:
```bash
$ docker-compose up -d #builds and runs the docker image in background
$ docker-compose exec sugarbuild ./osbuild pull # ./osbuild pull
$ docker-compose exec sugarbuild ./osbuild run # ./osbuild run
```

I know docker containers can use the host X server if the container have enough permissions (e.g. running `xhost +`), but this is the error I'm getting:
```log
Type Shift-Alt-Q inside sugar to close.

Command failed: sugar-runner

/code/build/out/install/bin/sugar-runner:28: PyGIWarning: SugarRunner was imported without specifying a version first. Use gi.require_version('SugarRunner', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import SugarRunner
/code/build/out/install/libexec/sugar-runner/xephyr-window:21: PyGIWarning: SugarRunner was imported without specifying a version first. Use gi.require_version('SugarRunner', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import SugarRunner
/code/build/out/install/bin/sugar-runner:46: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk

xinit: XFree86_VT property unexpectedly has 0 items instead of 1
/code/build/out/install/libexec/sugar-runner/xinitrc:25: PyGIWarning: SugarRunner was imported without specifying a version first. Use gi.require_version('SugarRunner', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import SugarRunner
Warning:          Key <OUTP> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I255> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
xinit: connection to X server lost


! Failed to run command run
```

I'm currently using OpenSuse Leap 42.1, `uname -a`:
```
Linux linux-e4p7.suse 4.1.34-33-default #1 SMP PREEMPT Thu Oct 20 08:03:29 UTC 2016 (fe18aba) x86_64 x86_64 x86_64 GNU/Linux
```

Dockerfile:
```Dockerfile
FROM fedora:23
RUN mkdir /code/
# Install sugar-build dependencies
RUN dnf install -y \
    python \
    python-devel \
    python-virtualenv \
    python-gobject \
    libXrandr \
    tar \
    xz \
    npm \
    sudo && \
    dnf clean all --enablerepo=\*
WORKDIR /code/

# Add sugar as user and sudoer
RUN useradd -ms /bin/bash sugar && echo ' sugar ALL=(ALL)   NOPASSWD:ALL' >> /etc/sudoers
USER sugar
VOLUME ["/code/"]
ENTRYPOINT ["tail -f /dev/null"]
```
docker-compose.yml:
```yml
#  
#  USAGE:
#  - Build and run the container:
#       docker-compose up -d
#  _ Execute commands:
#       docker-compose exec sugarbuild <command>
#       e.g:
#           docker-compose exec sugarbuild ./osbuild pull
#           docker-compose exec sugarbuild ./osbuild run
#

sugarbuild:
    build: .
    volumes:
        - ./:/code/
        - /tmp/:/tmp/ # Required to run GUI
        - /dev/snd:/dev/snd # Required to run GUI
    privileged: true
    entrypoint: # no-op to keep container up
        - tail
        - -f
        - /dev/null
    # Allow tty and stdin input
    stdin_open: true
    tty: true
    # Use current display
    environment:
        - DISPLAY=$DISPLAY
    net: "host"
    pid: "host"
    ipc: "host"
```

All my files are available [here](https://gist.github.com/nemesiscodex/9414209fe9e3febded4e7d2ed5ada7e6)

**Comment by quozl** [comment]
sugar-build is an chrooted emulator.  Running an emulator inside a docker seems a bit redundant, not to mention inefficient and prone to strangeness.  Why not run Sugar native within docker?  Sugar is normally run native by users.

**Comment by i5o** [comment]
@nemesiscodex is there anything in sugar-build/home/logs/shell.log ?
Can you attach that file? There may be some error in the code itself

**Comment by nemesiscodex** [comment]
@quozl, Is that the way it behaves if you are running sugar-build directly on fedora? 
If this is a waste of time, I will just try to setup the dev environment manually. I may be able to reuse some of the scripts from sugar-build.

@i5o that file doesn't exist, but I found another in `sugarbuild/home/dotsugar/default/logs/shell.log`
```log
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/code/build/out/install/lib/python2.7/site-packages/jarabe/main.py", line 61, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

```

**Comment by quozl** [comment]
@nemesiscodex, you're missing a dependency, is all.  Add WebKit and it should work.  I don't recommend running sugar-build on Fedora.  Instead use the Fedora or Debian packages of Sugar.  When a later version of Sugar is needed, either (a) work with the Fedora or Debian team who do packages, or (b) substitute the tarball of the later version into the existing Fedora or Debian package.

**Comment by i5o** [comment]
@nemesiscodex weird, I thought I added that dependency to the install proccess :(

Anyway sudo dnf install webkitgtk or libwebkitgtk or something like that should work; if not, just remove that line in the sugar code

**Comment by i5o** [comment]
@nemesiscodex anyway, if you find the dependency please comment it here, so I can add it to the auto-install process

**Comment by quozl** [comment]
@i5o, although removing that line doesn't fix the underlying problem; View Help in the shell uses WebKit. :grin: You can find the list of dependencies in the Fedora and Debian packages for Sugar. We used to maintain it on wiki.sugarlabs.org, but the recent releases deprecated maintenance.

**Comment by i5o** [comment]
@quozl I thought we used WebKit2 for viewhelp and stuff..

**Comment by quozl** [comment]
@i5o why stop it working with WebKIt?  Same warning that @nemesiscodex pasted above was the trigger for https://github.com/sugarlabs/sugar/pull/723 which once merged will not cause the warning, because the require_version is in an exception handler.

**Comment by quozl** [comment]
@i5o we still have to have WebKit in sugar-toolkit-gtk3 to support older activities.

**Comment by nemesiscodex** [comment]
Installed `webkitgtk3` and it worked! thanks!
