### ISSUE TITLE
run command showing too many errors and warnings in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Himanshu40** [sugarlabs/sugar-build#49]
```
himanshu@Asus-X556UF:~/sugar-build$ ./osbuild shell

$ sudo broot run osbuild shell

= Available commands =

karma
build
docs
run
check
dist
clean
pull

See also http://developer.sugarlabs.org/dev-environment.md.html
[osbuild sugar-build]$ build
[osbuild sugar-build]$ run
Type Shift-Alt-Q inside sugar to close.

Command failed: sugar-runner


Initializing built-in extension Generic Event Extension
Initializing built-in extension SHAPE
Initializing built-in extension MIT-SHM
Initializing built-in extension XInputExtension
Initializing built-in extension XTEST
Initializing built-in extension BIG-REQUESTS
Initializing built-in extension SYNC
Initializing built-in extension XKEYBOARD
Initializing built-in extension XC-MISC
Initializing built-in extension XINERAMA
Initializing built-in extension XFIXES
Initializing built-in extension RENDER
Initializing built-in extension RANDR
Initializing built-in extension COMPOSITE
Initializing built-in extension DAMAGE
Initializing built-in extension MIT-SCREEN-SAVER
Initializing built-in extension DOUBLE-BUFFER
Initializing built-in extension RECORD
Initializing built-in extension DPMS
Initializing built-in extension X-Resource
Initializing built-in extension XVideo
Initializing built-in extension XVideo-MotionCompensation
Initializing built-in extension SELinux
xinit: XFree86_VT property unexpectedly has 0 items instead of 1
Warning:          Key <OUTP> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          Key <I255> not found in evdev+aliases(qwerty) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I161> (keycode 161)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used
xinit: connection to X server lost

[osbuild sugar-build]$
```

**Comment by quozl** [comment]
Those warnings are not from `sugar-build`.  Those warnings are from `xephyr`, which is used by `sugar-build`.  The warnings occur normally.  Therefore there is no problem.  Or do you have some other problem?

If your problem is that Sugar does not start, please check `home/dotsugar/default/logs` as described in the [developer documentation](https://developer.sugarlabs.org/dev-environment.md.html#log%20files).

**Comment by Himanshu-Sekhar-Nayak** [comment]
Checked the logs, it shows these errors:-
```
himanshu@Asus-X556UF:~/sugar-build/home/dotsugar/default/logs$ cat shell.log 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/main.py", line 74, in <module>
    from jarabe.view import keyhandler
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/keyhandler.py", line 32, in <module>
    from jarabe.journal import journalactivity
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/journalactivity.py", line 45, in <module>
    from jarabe.journal.volumestoolbar import VolumesToolbar
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/volumestoolbar.py", line 42, in <module>
    from jarabe.view.palettes import VolumePalette
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/palettes.py", line 38, in <module>
    from jarabe.view.viewhelp import setup_view_help
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/viewhelp.py", line 46, in <module>
    from jarabe.view.viewhelp_webkit2 import Browser
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/viewhelp_webkit2.py", line 21, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 80, in require_version
    (namespace, version))
ValueError: Namespace WebKit2 not available for version 4.0
```

**Comment by quozl** [comment]
As now pointed out by our  [developer documentation](https://developer.sugarlabs.org/dev-environment.md.html), `sugar-build` is a chroot which tries to bring all dependencies into the same tree, in order to avoid having to deal with dependencies.

However, it has failed to keep up with a dependency in Sugar on WebKit2 GI API 4.0, and that is the underlying cause of your problem.

Or `sugar-build` seems to be Fedora specific.

Your choices are;

* use @i5o's Ubuntu branch, see https://github.com/i5o/sugar-build/commits/ubuntu

or

* use the [packaged style](https://developer.sugarlabs.org/dev-environment.md.html#setup%20a%20development%20environment%20-%20packaged%20style) development environment, which is much simpler than the chroot style you began with.

I can't tell you which of these is best, because I don't know why you are doing this.

If you have a fix for `sugar-build` please make a pull request.

**Comment by Himanshu-Sekhar-Nayak** [comment]
okay @quozl , I will look into packaged style, but this error is showing in Ubuntu :+1:

**Comment by quozl** [comment]
Yes, the error is showing on your Ubuntu 16.04 system, but it doesn't show on my Ubuntu 16.04 system, and the main difference is that I'm not using the `sugar-build` Fedora chroot you are using.  Instead, I'm using the Sugar packages for Ubuntu.

**Comment by Himanshu-Sekhar-Nayak** [comment]
So I will use `sugar-build` packages for Ubuntu. Thanks quozl :)

**Comment by Himanshu-Sekhar-Nayak** [comment]
Thanks quozl I will look into old commits as soon as possible :)

**Comment by icarito** [comment]
@Himanshu-Sekhar-Nayak , I think you didn't understand @quozl . 
Sugar-build is likely broken on Ubuntu. It's only a not-well-maitained development tool supported on Fedora, that tries to automate building individual Sugar components. I understand you might not want to switch distributions and I sympathize. One way to work around it is to install each package manually (and dependencies).

**Comment by icarito** [comment]
i.e. no need to look at old commits...

**Comment by icarito** [comment]
flashback of 10 years ago and trying jhbuild on Ubuntu... :-D

**Comment by Himanshu-Sekhar-Nayak** [comment]
okay @icarito 
but I use packaged style for development of activities. If I have a fix I will report you soon :+1:

**Comment by quozl** [comment]
@icarito, activity here today seemed to have been spawned by a detailed discussion on IRC, so I'll paste this for context;

```
[11:34:39] --> Himanshu40 (653f6601@gateway/web/cgi-irc/kiwiirc.com/ip.101.63.102.1) has joined #sugar
[11:35:03] <Himanshu40> Hey guys :)
[11:35:09] <Quozl`> Himanshu40: hello.
[11:35:25] <Himanshu40> hi Quozl`
[11:35:35] <Himanshu40> it's been long to see you
[11:35:39] <Himanshu40> how are you?
[11:36:03] <Quozl`> Himanshu40: fine thanks.  sorry if i don't remember you, i'm not very good at remembering, unless i keep notes and logs.  ;-)
[11:36:33] <Himanshu40> I am a Google Codein participant
[11:36:56] <walterbender> Quozl`, organization or account, the issue is that to me it isn't obvious that it is GitHub
[11:37:02] <Quozl`> Himanshu40: did you have fun?
[11:37:04] <Quozl`> walterbender: okay.
[11:37:35] <Quozl`> walterbender: i've added "GitHub" before `sugarlabs`, that should do it.  In next push, whenever.
[11:37:51] <Himanshu40> Hey walterbender
[11:37:55] <walterbender> thanks
[11:38:37] <Himanshu40> Yes Quozl`
[11:39:00] <Himanshu40> :)
[11:40:59] <Himanshu40> btw Quozl` is Sugar-dev evvironment chroot style running well in your Ubuntu 16.04 LTS
[11:41:01] <Himanshu40> ??
[11:41:59] <Quozl`> Himanshu40: i do not use chroot style sugar-build, because it is based on an old version of fedora long since out of support.  osbuild uses an old directory on sugarlabs.org to get the latest build, but there has been no build for some years.
[11:42:18] <Himanshu40> oh.......
[11:42:19] <Quozl`> Himanshu40: but mainly i don't use it because that's not how children use Sugar.
[11:42:35] <Himanshu40> okay
[11:42:42] <Quozl`> Himanshu40: i use packaged or native styles.  packaged styles on vm and real hardware.
[11:43:02] <Quozl`> Himanshu40: i use native style to make the packages, using fedora rpmbuild or debian git-buildpackage.
[11:43:03] <Himanshu40> I used packaged style and it's awesome
[11:43:30] <Quozl`> Himanshu40: it depends on why you need the environment; for activity development, all those methods should work, subject to whatever bugs they have.
[11:43:49] <Himanshu40> btw chroot style was running well during Google codein
[11:43:55] <Quozl`> Himanshu40: for development of sugar toolkit or sugar itself, native or chroot are the options.
[11:44:06] <Quozl`> Himanshu40: yes, but the repositories have changed since.
[11:44:16] <Himanshu40> now I understand
[11:44:35] <Quozl`> Himanshu40: if you went back in time to that date (using git checkout carefully), you might be able to make it work, then move each repository forward until you find what broke it.
[11:45:07] <Himanshu40> okay
[11:45:14] <Quozl`> Himanshu40: we do need people interested in keeping the chroot style working, but you have to find and fix the problems yourself, then publish or pull request.
[11:45:48] <Quozl`> Himanshu40: and there's still the underlying problem that the chroot is based on a build from years ago, while sugar has since changed to make it incompatible with that build.
[11:45:48] <Himanshu40> I remember during Google Codein a fix had been done by ignacio
[11:46:16] <Quozl`> Himanshu40: yes, you can find it in a branch of his repository; but a fix for ubuntu that breaks fedora isn't a good fix; the fix should work on both.
[11:47:10] <Himanshu40> here is that fix Quozl`
[11:47:11] <Himanshu40> https://github.com/sugarlabs/sugar-build/issues/47
[11:47:12] <gcibot_> [ not building in ubuntu · Issue #47 · sugarlabs/sugar-build · GitHub ]
[11:47:44] <Quozl`> Himanshu40: the chroot style environment is a big ask; a tough sell; because it is based on a chroot from years ago, to which a large number of repositories are checked out and built.  it is no wonder it breaks so easily.  it is like a tower of matchsticks.
[11:48:05] <Himanshu40> oh...
[11:48:17] <Himanshu40> btw
[11:48:32] <Himanshu40> I have to see for the recent change in that code
[11:48:36] <Quozl`> ... but at least after it falls down you have a pile of matchsticks you can use.
[11:49:04] <Himanshu40> okay :)
[11:50:10] <-- malverick__ (~Sumit@202.78.173.18) has quit (Ping timeout: 264 seconds)
[11:50:49] <Himanshu40> okay Quozl` I will look into it
[11:51:13] <Himanshu40> btw the latest commit is on 24Dec 2016 by ignacio
[11:51:29] <Quozl`> Himanshu40: as i said, you have to look at the commits in every single repository.
[11:51:44] <Himanshu40> okay
```

**Comment by icarito** [comment]
@Himanshu-Sekhar-Nayak one way to quickly find the commit you're looking for, is to look for git tags. Every release is tagged. Have fun!

**Comment by quozl** [comment]
@icarito, unfortunately several recent releases were not tagged, perhaps you'd like to add the tags?  :grin:

**Comment by icarito** [comment]
Sounds like fun.
Without knowing what is to be fixed it's impossible to recommend to work on master or find the release commit.

**Comment by Himanshu40** [comment]
btw you are right @icarito but I think the warning problem is may be this `gnome-keyring-daemon: insufficient process capabilities, unsecure memory might get used` . I will look into another problem as soon as possible

**Comment by icarito** [comment]
@Himanshu40 I guess you're still kicking `sugar-build`. As @quozl mentioned, those are errors of Xephyr, not the reason Sugar didn't start. That you will find in `~/.sugar/default/logs/shell.log`

**Comment by icarito** [comment]
under `sugar-build` that is in a different directory, I think `sugar-build/dotsugar/default/logs/shell.log`

**Comment by quozl** [comment]
The `gnome-keyring-daemon` warning is entirely normal, and nothing to do with Sugar not starting.  

About 14 days ago you identified the cause as

```
ValueError: Namespace WebKit2 not available for version 4.0
```

Which should be an easy thing to fix; install version 4.0 of the WebKit2 Python GI API.  Sugar packages for Debian and Ubuntu already depend on this, and it is automatically installed.  `sugar-build` apparently does not.

**Comment by Himanshu40** [comment]
So @quozl sugar-build need file changes for version 4.0 of the webkit2 Python GI API which is used by Debian and Ubuntu

**Comment by quozl** [comment]
Good try at paraphrasing, but I'm not sure you've caught on.  I'll rephrase.

Sugar itself depends on version 4.0 of the WebKit2 Python GI API.  Your error message from shell.log confirms that.  Sugar commits also confirm that.  Sugar packaged by Debian developers declares that dependency and it is satisfied automatically when you type `apt install sucrose`.

`sugar-build` declares a dependency on a Fedora package `libwebkit2gtk`.  `sugar-build` is anchored on Fedora 23.  I don't know what version of the WebKit2 Python GI API it is, but assuming the dependency is satisfied your error shows that it isn't version 4.0, so it is probably 3.0.

To fix it you would have to install Fedora 23, and figure out which package (if any) satisfies the dependency.  Or, install Fedora 25, and do the same.  Both of which seem way more complicated than installing Ubuntu packages of Sugar on your Ubuntu system. :grin:

**Comment by Himanshu40** [comment]
Thanks @quozl when I will try I will report asap :100:

**Comment by Himanshu40** [comment]
Finally it worked by giving version 3 in webkit2. Thanks @quozl :) :+1:

**Comment by quozl** [comment]
Good news, thanks.  Can you say exactly what you did so that others can do it?

**Comment by quozl** [comment]
> Can you say exactly what you did so that others can do it?

Answered in IRC #sugar channel; the workaround was to revert `sugar` to an earlier WebKit2 API, and the root cause is that `sugar-build` needs maintenance.

```
<Quozl`> Himanshu40: g'day.

<Himanshu40> hi Quozl`

<Himanshu40> finally I fixed that issue

<Himanshu40> given version 3 and now its working

<Quozl`> Himanshu40: what do you mean given version 3?

<Himanshu40> https://github.com/sugarlabs/sugar-build/issues/49

<Quozl`> Himanshu40: yes, i know which issue you mean, but you did not
say what you did, that's why i asked on the issue what you did.

<Quozl`> Himanshu40: where's a pull request?

<Himanshu40> I changed in the viewhelp_webkit2.py in line 21

<Himanshu40> here is the change

<Himanshu40> gi.require_version('WebKit2', '3.0')

<Quozl`> Himanshu40: well, that's not a fix.  Later versions of Fedora
and Ubuntu have version 4.0 of WebKit2, and Fedora have said version
3.0 is deprecated.

<Quozl`> Himanshu40: even the version 3.0 Fedora package has been
abandoned and wiped out.

<Himanshu40> I think I should keep both version 3 and 4 too to work

<Quozl`> Himanshu40: what are the API changes from 3.0 to 4.0?

<Quozl`> Himanshu40: does Sugar View Help use any 4.0 API features
that are not available in 3.0 API?

<Himanshu40> tried in 4 but not worked

<Himanshu40> when changed to 3 it worked

<Quozl`> Himanshu40: but it only "not worked" because you didn't
install WebKit2 4.0 API, right?

<Quozl`> Himanshu40: have you tried to install WebKit2 4.0 API yet?

<Himanshu40> nopes

<Quozl`> heh.

<Himanshu40> let's I try it

<Quozl`> Himanshu40: https://src.fedoraproject.org/cgit/rpms/?q=webkit
are all the Fedora packaging repositories for WebKit related packages.

<Quozl`> Himanshu40:
https://src.fedoraproject.org/cgit/rpms/webkitgtk4.git/ is the WebKit2
4.0 API packaging repository.

<Quozl`> Himanshu40:
https://src.fedoraproject.org/cgit/rpms/webkitgtk4.git/log/?h=f23 is
the Fedora 23 branch of the repository; mentioned because sugar-build
is currently aligned and synchronised to Fedora 23.

<Quozl`> Himanshu40:
https://src.fedoraproject.org/cgit/rpms/webkitgtk4.git/tree/webkitgtk4.spec?h=f23
is the spec file for Fedora 23 build of WebKit2 4.0 API

<Himanshu40> I think I should use it

<Himanshu40> by running this

<Himanshu40> sudo apt-get install gir1.2-webkit2-4.0

<Quozl`> Himanshu40: but sugar-build is a fedora 23 chroot, so what
you do in the outer operating system (ubuntu) may or may not impact
... yes, it looks like sugar-build build/root.json says
"libwebkit2gtk"

<Himanshu40> lets I try it by using that command

-*- Himanshu40 installing webkit2 of version 4

<Quozl`> Himanshu40: yes, try it.

<Quozl`> Himanshu40: meanwhile i am checking fedora 25 vm to make sure
package name for future sugar-build.

<Himanshu40> okay

<Quozl`> Himanshu40: fedora 25 vm uses package name webkitgtk4, as
expected.

<Himanshu40> okay

<Quozl`> Himanshu40: there is no libwebkit2gtk package.

<Himanshu40> oh......

<Quozl`> (on fedora 25, that is).

<Quozl`> Himanshu40: so sugar-build is old, unmaintained, out of date.

<Himanshu40> yes you are right Quozl`

<Himanshu40> +1

<Quozl`> Himanshu40: if you think sugar-build is useful, then maintain
it; adjust it to use fedora 25 or fedora 26, and resolve all the
dependencies one by one, and adjust root.json, then once it works,
make a pull request.

<Himanshu40> mine is showing in ubuntu :- gir1.2-webkit2-4.0 is
already the newest version (2.16.1-0ubuntu0.16.04.1)

<Quozl`> Himanshu40: exactly my point; when you use sugar-build,
anything you do outside sugar-build (like in ubuntu) is ignored.

<Himanshu40> oh........

<Quozl`> Himanshu40: sugar-build is a chroot, an artificial emulator.

<Himanshu40> oh.....

<Himanshu40> okay

<Quozl`> Himanshu40: look at build/root.json in sugar-build, you will
see it makes chroot from fedora 23.

<Himanshu40> yes you are right

<Quozl`> Himanshu40: fedora 23 is quite old now, and yet
github/sugarlabs/sugar has moved on.

<Himanshu40> here it is "distro": "fedora-23"

<Himanshu40> I think lets have a update of this sugar-build to new

<Himanshu40> Fedora 25

<Quozl`> Himanshu40: sure, you can do that, but might be big job, and
when you hit problem you may have to fix it yourself.  but a good
guide is to install fedora 25 in a vm, install sugar packages, then
remember the package list.

<Himanshu40> okay

<Quozl`> Himanshu40: http://wiki.sugarlabs.org/go/Fedora explains how
to add Sugar to a Fedora 25 VM.

<gcibot_> [ Fedora - Sugar Labs ]

<Quozl`> Himanshu40: and you'll see in those instructions how
webkitgtk3 has to be added manually; this is because the Fedora
package of Sugar 0.110 has a bug; it does not say it depends on
webkitgtk3 but it should.

<Quozl`> Himanshu40: also, since 0.110, github/sugarlabs/sugar has
changed to use webkitgtk4.

<Quozl`> ... so it will be ready for Fedora 26.

<Himanshu40> oh......

<Quozl`> (Fedora 26 is due on 2017-06-27).

<Himanshu40> yes

<Quozl`> Any questions?

<Himanshu40> I need to get Fedora25 for testing so I can use in vm

<Quozl`> Sure.
```

**Comment by Himanshu40** [comment]
So it needs a update to work smoothly in Fedora 25 @quozl

**Comment by samswag** [comment]
i was trying to run the build command on Ubuntu 16.04 i keep getting this errors.
See also http://developer.sugarlabs.org/dev-environment.md.html
[osbuild sugar-build]$ build

= Building =

* Building automake
* Building gwebsockets
* Building sugar-docs
* Building sugar-base
* Building sugar-toolkit
* Building sugar-toolkit-gtk3
* Building sugar
* Building sugar-artwork
* Building sugar-datastore
* Building sugar-runner
* Building sugar-web
* Building sugar-web-test
* Building sugar-web-template
* Building docker
* Building browse
* Building write

Command failed: python2.7 /home/broot/sugar-build/write/setup.py install --prefix /home/broot/sugar-build/build/out/install

/home/broot/sugar-build/write/po/bn_IN.po:243:10: syntax error
msgfmt: found 1 fatal error
ERROR - msgfmt failed with return code 1.
Traceback (most recent call last):
  File "/home/broot/sugar-build/write/setup.py", line 21, in <module>
    bundlebuilder.start()
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 678, in start
    globals()['cmd_' + options.command](config, options)
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 563, in cmd_install
    installer.install(options.prefix, options.install_mime)
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 339, in install
    self.builder.build()
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 182, in build
    self.build_locale()
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/sugar3/activity/bundlebuilder.py", line 214, in build_locale
    cat = gettext.GNUTranslations(open(mo_file, 'r'))
IOError: [Errno 2] No such file or directory: '/home/broot/sugar-build/write/locale/bn_IN/LC_MESSAGES/org.laptop.AbiWordActivity.mo'

**Comment by quozl** [comment]
@samswag, in future, please use three backticks lines around log, so it does not wrap badly.  Like

\`\`\`
this
\`\`\`

What you saw is an entirely different thing to what Himanshu40 saw.

The problem you saw is about the `po/bn_IN.po` file which was recently changed, so please post your issue to `sugar-toolkit-gtk3` or as a comment to the pull request which changed it;

* https://github.com/sugarlabs/sugar-toolkit-gtk3
* https://github.com/sugarlabs/sugar-toolkit-gtk3/pull/364

Neither Walter nor I are testing pull requests against `sugar-build` before merging; if that's something you can do, please get involved in the pull request reviews for each module.

**Comment by quozl** [comment]
Woah, sorry, wrong change.  It was https://github.com/sugarlabs/write-activity/pull/17 in https://github.com/sugarlabs/write-activity made 18 days ago.

**Comment by quozl** [comment]
@samswag please test again with https://github.com/sugarlabs/write-activity/pull/18

**Comment by Himanshu40** [comment]
Yes you are correct @quozl and I removed `Write-Activity` in `modules.json` So that I can build it. Now it's working well :) :+1:

**Comment by i5o** [comment]
I will try to fix the current issues with sugar-build asap, I haven't
been very active lately.

But I'll rate to encourage the usage of fedora, or latest ubuntu
versions (see 17.04) to basically build sugar build without broot

**Comment by samswag** [comment]
Yeah you are right nacio! I am running Sugar on Fedora 25 without any problem.

**Comment by quozl** [comment]
Is there a fix for `sugar-build` yet for this problem?  (In brief, the problem is that `sugar-build` lists an old dependency that `sugar` has since upgraded from.)

**Comment by iamutkarshtiwari** [comment]
@quozl @i5o I am also facing unprecedent errors while trying to setup a fresh clone of Sugar-build. Seems like a recent change in one of it's modules is causing the issue.

**Comment by quozl** [comment]
@iamutkarshtiwari, please show us `shell.log`.  What you posted is *normal* output from `xephyr` which is used by `sugar-runner`.

**Comment by iamutkarshtiwari** [comment]
@quozl Here is the output from shell.log - 

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/main.py", line 74, in <module>
    from jarabe.view import keyhandler
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/keyhandler.py", line 32, in <module>
    from jarabe.journal import journalactivity
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/journalactivity.py", line 45, in <module>
    from jarabe.journal.volumestoolbar import VolumesToolbar
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/journal/volumestoolbar.py", line 42, in <module>
    from jarabe.view.palettes import VolumePalette
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/palettes.py", line 38, in <module>
    from jarabe.view.viewhelp import setup_view_help
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/viewhelp.py", line 46, in <module>
    from jarabe.view.viewhelp_webkit2 import Browser
  File "/home/broot/sugar-build/build/out/install/lib/python2.7/site-packages/jarabe/view/viewhelp_webkit2.py", line 21, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib64/python2.7/site-packages/gi/__init__.py", line 80, in require_version
    (namespace, version))
ValueError: Namespace WebKit2 not available for version 4.0
```

Seems to be the same webkit version error as stated by Himanshu

**Comment by quozl** [comment]
@iamutkarshtiwari, agreed, same problem; feel free to find a solution, but for me I don't use `sugar-build`, I use native packages, which have the advantage of testing the complete system; Sugar and the distribution, without emulation.  It isn't in my interest to reduce the testing of the native environment.  http://developer.sugarlabs.org/ has been adjusted to show the alternate development environments.

**Comment by iamutkarshtiwari** [comment]
@quozl If you suggest, I can go ahead and create a PR with modified `gi.require_version('WebKit2', '4.0')` to **3.0** to prevent sugar-build from crashing?

**Comment by Himanshu40** [comment]
Can you @iamutkarshtiwari and me rebuild `sugar-build` ?

**Comment by quozl** [comment]
@iamutkarshtiwari, certainly not.  Fix `sugar-build`, not `sugar`.  `sugar-build` is only an emulator, and is not used very much at all.  `sugar` is used by the most people.
